name: Deploy

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - run: npm install
      - run: npx tailwindcss -i ./src/styles.css -o ./static/styles.css --build

      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install trunk
      - run: trunk build --release --public-url /yew-reversi

      - run: cp -r ./dist/ ./public/
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
